### ISSUE TITLE
Deep relations not working

### ISSUE THREAD

**Issue by flavsxavier** [Joao-ava/react-rsql-query-builder#3]
Isn't possible to filter relations with 2 levels or more, only 1 level.

For example, assuming we have entities `User`, `Role` and `Permission` with the following schema:
- User has Role
- Role has Permissions

If we try to filter a `User` by `Role.name` (1 level relation) it will work.
If we try to filter a `User` by `Role.permission.name` (2 levels relation) it will not work.

**Comment by Joao-ava** [comment]
This issue is in the backend of the [typeorm adapter library](https://github.com/Joao-ava/rsql-typeorm), fixed in version [v1.2.8](https://github.com/Joao-ava/rsql-typeorm/tree/v1.2.8).
